### ISSUE TITLE
[Bug]: iconv.h missing

### ISSUE THREAD

**Issue by timstrom** [termux-play-store/termux-packages#2]
### Problem description

iconv.h is missing.

That may be caused by the following command

TERMUX_PKG_RM_AFTER_INSTALL="include/iconv.h"

in
termux-packages/packages/libiconv/build.sh

iconv.h seems not to be provided by other packages.

### What steps will reproduce the bug?

apt install libiconv

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.127
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.6
Android version:
14
Kernel build information:
Linux localhost 5.15.137-android14-11-gbf4f9bc41c3b-ab11664771 #1 SMP PREEMPT Wed Apr 3 07:16:23 UTC 2024 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 8 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
Thanks for the clear report!

`iconv.h` is meant to be included with the `ndk-sysroot` package, and should now be fixed in https://github.com/termux-play-store/termux-packages/commit/4b91078ea8486367568143b7e434c90b60a4428e - update to the latest `26d-1` version of `ndk-sysroot` with `pkg up`.

Let me know how it works! Note that iconv is currently provided by the system libc (in the Google Play build of Termux, which targets newer Android versions), so no external libraries are necessary.

- Not sure if the system iconv functions is a good enough replacement for GNU libiconv, so happy to hear feedback!
- If we're going for iconv provided by the system as now, perhaps that can be improved by setting up `libiconv.so` as a no-op library, and perhaps remove the GNU libiconv package?

**Comment by timstrom** [comment]
Thank you for the quick response.

There seems to be something 'wrong' with the system iconv.h from ndk-sysroot.

I am trying to compile the statistic program R (R-4.4.1.tar.gz).

This works on F-Droid Termux, when I use the following command to configure the Makefile:

CC=clang CXX=clang++ FC=flang-new LD=lld ./configure --with-x=no --enable-R-shlib --prefix=$PREFIX/local/R-4.4.1


If I use the same command on play-store Termux, the configure script stops with the following error:

checking for iconv.h... yes
checking for iconv... yes
checking whether iconv accepts "UTF-8", "latin1", "ASCII" and "UCS-*"... no
configure: error: a suitable iconv is essential

The configure script and make run successfully when I install the libiconv package from  F-Droid Termux locally:

dpkg -i -force-overwrite libiconv_1.17_aarch64.deb

**Comment by fornwall** [comment]
@timstrom Thanks a lot for the detailed steps - will look into this tomorrow!

**Comment by fornwall** [comment]
Indeed, the iconv functionality provided by the bionic libc is quite limited: https://android.googlesource.com/platform/bionic.git/+/refs/heads/main/libc/bionic/iconv.cpp, only 

```c++
  if (__match_encoding(s, "utf8")) {
    *encoding = UTF_8;
  } else if (__match_encoding(s, "ascii") || __match_encoding(s, "usascii")) {
    *encoding = US_ASCII;
  } else if (__match_encoding(s, "utf16le")) {
    *encoding = UTF_16_LE;
  } else if (__match_encoding(s, "utf16be")) {
    *encoding = UTF_16_BE;
  } else if (__match_encoding(s, "utf32le")) {
    *encoding = UTF_32_LE;
  } else if (__match_encoding(s, "utf32be")) {
    *encoding = UTF_32_BE;
  } else if (__match_encoding(s, "wchart")) {
    *encoding = WCHAR_T;
  } else {
    return false;
  }
``` 

While the test program run by R:s configure is:

```C
int main (void) {
  iconv_t cd;
  cd = iconv_open("latin1","UTF-8");
  if(cd == (iconv_t)(-1)) {printf("latin1 UTF-8\n"); exit(1); }
  iconv_close(cd);
  cd = iconv_open("UTF-8","latin1");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("","latin1");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("","UTF-8");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("latin1", "");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("UTF-8","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("ASCII","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("UCS-2LE","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("", "UCS-2LE");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("UCS-2BE","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("", "UCS-2BE");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("UCS-4LE","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("", "UCS-4LE");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("UCS-4BE","");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  cd = iconv_open("", "UCS-4BE");
  if(cd == (iconv_t)(-1)) exit(1);
  iconv_close(cd);
  exit(0);
}
```

Will most likely go back to letting the more fully featured GNU libiconv package provide iconv, instead of the more limited built-in bionic functionality.

**Comment by timstrom** [comment]
Thanks. Would make it easier to compile the R package.

**Comment by fornwall** [comment]
@timstrom https://github.com/termux-play-store/termux-packages/commit/8e8d2b7c2bdab62616192cec184edd16e1dec1a8 changes back so that `iconv.h` is provided by the `libiconv` package - if you run `pkg up`, does it work better?

**Comment by timstrom** [comment]
iconv.h of the libiconv package works for the configuration of the Makefile.

But
Since June 20 it is not longer possible to compile (make) the R-packages. I get errors like 

sh: /data/data/com.termux/files/usr/bin/make: Permission denied
sh: /data/data/com.termux/files/usr/bin/make: Permission denied

May be, it is caused by the upgrades of termux.exec or termux-tools on June 20.

Some libraries can be compiled, others not.

Make finishes with the following error message:

`begin installing recommended package MASS
* installing *source* package ‘MASS’ ...
** package ‘MASS’ successfully unpacked and MD5 sums checked
** using non-staged installation
** libs
sh: /data/data/com.termux/files/usr/bin/make: Permission denied
Warning in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  :
  running command '/data/data/com.termux/files/usr/bin/make -f '/data/data/com.termux/files/home/Downloads/R-4.4.1/etc/Makeconf' -f '/data/data/com.termux/files/home/Downloads/R-4.4.1/share/make/shlib.mk' compilers' had status 126
sh: --version: inaccessible or not found
sh: /data/data/com.termux/files/usr/bin/make: Permission denied
ERROR: compilation failed for package ‘MASS’
* removing ‘/data/data/com.termux/files/home/Downloads/R-4.4.1/library/MASS’
sh: /data/data/com.termux/files/usr/bin/rm: Permission denied
make[2]: *** [Makefile:53: MASS.ts] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/Downloads/R-4.4.1/src/library/Recommended'
make[1]: *** [Makefile:39: recommended-packages] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/Downloads/R-4.4.1/src/library/Recommended'
`

**Comment by fornwall** [comment]
> Since June 20 it is not longer possible to compile (make) the R-packages. I get errors like
>  sh: /data/data/com.termux/files/usr/bin/make: Permission denied
>  sh: /data/data/com.termux/files/usr/bin/make: Permission denied
> May be, it is caused by the upgrades of termux.exec or termux-tools on June 20.

@timstrom Thanks a lot! I think the just released [version 1.4](https://github.com/termux-play-store/termux-exec/releases/tag/1.4) of `termux-exec` fixes the issue you've seen here, when you have the time please run `pkg up` to update and check how it works!

**Comment by timstrom** [comment]
It works. Thank you.

**Comment by fornwall** [comment]
Thanks for following up!
