### ISSUE TITLE
[Bug]:  flang version mismatch

### ISSUE THREAD

**Issue by timstrom** [termux-play-store/termux-packages#3]
### Problem description

flang can not be installed because of version mismatch.

termux-packages/packages/flang/build.sh
requires 
TERMUX_PKG_DEPENDS="libc++, libllvm (= $TERMUX_PKG_VERSION), clang (= $TERMUX_PKG_VERSION), lld (= $TERMUX_PKG_VERSION), mlir (= $TERMUX_PKG_VERSION)"

$TERMUX_PKG_VERSION is 18.1.7
but
libllvm, clang, lld and mlir
are version 18.1.7-1

The same mismatch is present in F-Droid termux.

### What steps will reproduce the bug?

pkg install flang

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_EXEC__PROC_SELF_EXE=/data/data/com.termux/files/usr/bin/termux-info
TERMUX_VERSION=0.127
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
Updatable packages:
All packages up to date
termux-tools version:
3.0.6
Android version:
14
Kernel build information:
Linux localhost 5.15.137-android14-11-gbf4f9bc41c3b-ab11664771 #1 SMP PREEMPT Wed Apr 3 07:16:23 UTC 2024 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 8 Pro
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by fornwall** [comment]
Thanks! Should be fixed by https://github.com/termux-play-store/termux-packages/commit/5214cabb9c6d89413446a5de8f76e4324653c7d8 now (need a more robust way to avoid the problem in the future though).

I'll submit the fix to the F-Droid package repo.
