### ISSUE TITLE
[Bug]: There is no build-bootstraps.sh file in this project.

### ISSUE THREAD

**Issue by RainPlayer** [termux-play-store/termux-packages#4]
### Problem description

i want to build my custom package(like "com.mytermux") bootstrap-aarch64.zip, but there is no build-bootstraps.sh file. is there another way to build my own bootstrap-aarch64.zip? if the answer is yes, let me know, thank you.

### What steps will reproduce the bug?

no build-bootstraps.sh file

### System information

```shell
linux
```

**Comment by fornwall** [comment]
From matrix chat, where this was confirmed to work:

> Just pushed an update to scripts/generate-bootstraps.sh - can you try the newly introduced -b/--build option there and see how it works?
> It will build bootstrap packages locally, so you probably want to run it inside a docker container (./scripts/run-docker.sh)
> Will output bootstrap-aarch64.zip and bootstrap-x86_64.zip in the current directory
> You can limit architecture to aarch64 if you want to speed things up during development: ./scripts/generate-bootstraps.sh --build --architectures aarch64
