### ISSUE TITLE
[Package]: TUR

### ISSUE THREAD

**Issue by Usinganame** [termux-play-store/termux-packages#6]
### Why is it worth to add this package?

The TUR (Termux User Repository) Is available in the Github and F-droid release of Termux, but not the Google Play

### Home page URL

https://github.com/termux-user-repository/tur

### Source code URL

https://github.com/termux-user-repository/tur

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by fornwall** [comment]
Thanks, it's available now - run `pkg up` to update to latest packages, and then you should be able to add TUR with `pkg install tur-repo`.

There may be some issues with some TUR packages due to the updated `targetSdk` on Google Play, let me know how it works and I can look into any problem.

**Comment by Usinganame** [comment]
It works now. Thanks
